[package]
name = "ssimulacra2-rs"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_ssimulacra2"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module", "generate-import-lib"] }
num-traits = "0.2.19"
rayon = { version = "1.11.0" }
thiserror = "2.0.17"
yuvxyb = "0.4.2"
jxl_simd = { version = "0.2.2", features = ["all-simd"] }

[build-dependencies.yuvxyb-math]
version = "0.1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
